GET http://localhost:8001/addJob/cliente-0-handlingMoved HTTP/1.1

###
GET http://localhost:8089/connect HTTP/1.1
###
GET http://localhost:8089/pause/cliente-0-handlingMoved HTTP/1.1
###
GET http://localhost:8089/resume/cliente-0-handlingMoved HTTP/1.1